# Generated automatically by Terraform after `terraform apply`.
# Keep this example for reference.
[app]
1.2.3.4 ansible_user=ubuntu ansible_ssh_private_key_file=/absolute/path/to/private_key

[app:vars]
artifacts_bucket=task-tracker-abcd1234
aws_region=us-east-1
