name: Deploy Zocket to PROD

on:
  workflow_dispatch:
    inputs:
      version:
          description: "Image version tag (default: latest)"
          required: false
          default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECS_API_CLUSTER: ${{ vars.ECS_CLUSTER }}
      ECS_API_SERVICE: ${{ vars.ECS_SERVICE }}
      ECS_API_TASK: ${{ vars.ECS_TASK }}
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      ECR_IMAGE_TAG: ${{ github.event.inputs.version }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to ECS
        run: |
          TASK_DEF=$(aws ecs describe-task-definition --task-definition "$ECS_API_TASK" --query "taskDefinition" --output json)

          NEW_TASK_DEF=$(echo "$TASK_DEF" | jq \
            --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG" \
            '.containerDefinitions[0].image = $IMAGE |
             del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          NEW_TASK_ARN=$(aws ecs register-task-definition \
            --cli-input-json "$NEW_TASK_DEF" \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          aws ecs update-service \
            --cluster "$ECS_API_CLUSTER" \
            --service "$ECS_API_SERVICE" \
            --task-definition "$NEW_TASK_ARN" \
            --force-new-deployment

          aws ecs wait services-stable \
            --cluster "$ECS_API_CLUSTER" \
            --services "$ECS_API_SERVICE"
